id: P800A04AC
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: zh
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    47ac20f204084a0f86b0de72b580e75e:
      title: Advice to Lhawang Tashi
      parent: Advice
    5df23639b0dc41349ea5086a0dc63031:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    20bcce2f1ddb4e26a36ac379dfe2a48d:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    56a4a40821c2486e9958b5749598a4e7:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    6831176c1a234780990c1228ac054646:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    80abc1552e804f9da01c0b70c25d8293:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    bff8d543cbbc4ace8c1b2db4f6d9ed37:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    3d5b38e342c74d09bcaa275c0c99a314:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    5446e03092e7440d960b3c5a5ff9e7a4:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    4aec5b44b4544ba2b9e258a9e5b1c0cf:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    38862598e30d4f1085314984d42ef4dc:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    0949a2ccc0574f999167d7ac0b66564e:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    19e6a9e9738c4a90bc1d94aebeff9769:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    4a0d898936da469bb6a846a742b7f63b:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    ef9491ab1c62442db066257fc3884c01:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    4c2850f17cbe47459e8064a4bc8b20dd:
      title: A Short Supplication to Tārā
      parent: Prayers
    8b789df137974d508c7fc68f323f74eb:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    9e36cefb5df2437f85e209452b2eed08:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    0ce6d30c4eb64deb9022b4bb59bb6a70:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    343074a314404952ab72c0806f285cf2:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    b788ab1d41f14ff6a3221e83f2ee39b4:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    e325c63ee9a54507a08f7dd849cbd980:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    2e45a2d9bd8a4669bd6358f6a1bc6f6a:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    4166032227a64596a62b1af7d82507fd:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    86a00d1a085e4f1db26cb5f6147c7527:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.221896'
last_modified_at: '2022-02-28T23:32:21.221899'
